name       : libvirt
version    : 9.7.0
release    : 61
source     :
    - https://libvirt.org/sources/libvirt-9.7.0.tar.xz : d8c758fe7db640f572489caa8ea6dd8262d169a4372326c23a3a013cdc40b8ce
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
homepage   : https://libvirt.org/
component  : virt
summary    : Library providing a simple virtualization API
description: |
    A toolkit to interact with the virtualization capabilities of recent versions of Linux
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - pkgconfig(libcap-ng)
    - pkgconfig(libiptc)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libparted)
    - pkgconfig(libpcap)
    - pkgconfig(libssh)
    - pkgconfig(libtirpc)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pciaccess)
    - pkgconfig(yajl)
    - dmidecode
    - dnsmasq
    - ebtables
    - parted
    - python-docutils
    - rpcsvc-proto-devel
rundeps    :
    - dmidecode
    - dnsmasq
    - ebtables
    - parted
setup      : |
    %meson_configure \
        -Dchrdev_lock_files='/run/lock' \
        -Ddriver_interface=enabled \
        -Ddriver_libvirtd=enabled \
        -Ddriver_network=enabled \
        -Ddriver_qemu=enabled \
        -Dfirewalld=disabled \
        -Dinit_script='systemd' \
        -Drunstatedir='/run' \
        -Dselinux=disabled \
        -Dstorage_zfs=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 $pkgfiles/libvirt.sysusers $installdir/%libdir%/sysusers.d/libvirt.conf
    install -Dm00644 $pkgfiles/libvirt.tmpfiles $installdir/%libdir%/tmpfiles.d/libvirt.conf

    # Custom polkit rules
    rm -fv $installdir/usr/share/polkit-1/rules.d/50-libvirt.rules
    install -Dm00644 $pkgfiles/org.libvirt.rules $installdir/usr/share/polkit-1/rules.d/org.libvirt.rules

    rm -rf $installdir/usr/share/doc

    # ensure that .sockets will be always be activated after a (re)boot
    # TODO: .sockets currently stay de-activated even after a `systemctl daemon-reexec`
    install -dm00755 $installdir/usr/lib/systemd/system/sockets.target.wants
    ln -svf ../virtlockd.socket $installdir/usr/lib/systemd/system/sockets.target.wants/
    ln -svf ../virtlogd.socket $installdir/usr/lib/systemd/system/sockets.target.wants/
    ln -svf ../libvirtd.socket $installdir/usr/lib/systemd/system/sockets.target.wants/
    ln -svf ../libvirtd-ro.socket $installdir/usr/lib/systemd/system/sockets.target.wants/
